### ISSUE TITLE
Failed to log user in: no token

### ISSUE THREAD

**Issue by mainstringargs** [AquaticMasteryProductions/Robinhood-Api-Java#9]
When I try to login using this simple code:

```
	public static void main(String[] args) {
		
		RobinhoodApi api = null;
		try {
			api = new RobinhoodApi(<USER>,<PASSWORD>);
		} catch (RobinhoodApiException e) {
			e.printStackTrace();
		}
		
		System.out.println(api.getAccountData());
	}

```

I get this error:

```
com.ampro.robinhood.throwables.RobinhoodApiException: Failed to log user in: no token
	at com.ampro.robinhood.RobinhoodApi.<init>(RobinhoodApi.java:105)
	at com.ampro.robinhood.Test.main(Test.java:11)
Exception in thread "main" java.lang.NullPointerException
	at com.ampro.robinhood.Test.main(Test.java:17)
```

**Comment by JonoAugustine** [comment]
Since Robinhoods official API isn't public it's been pretty painful to keep this code up to date when they change it (I mean my last update was months ago) so there are likely more than a few broken things. I personally haven't even used it since RH made the last major update that changed a good portion on the API. I will look into this as soon as I can but if anyone finds a solution go ahead and let us know:alien:

**Comment by mainstringargs** [comment]
I've done a pull request that seems to work.

**Comment by JonoAugustine** [comment]
Thanks for the request, I will check it out as soon as I can. 👽
